### ISSUE TITLE
ultra sound relay

### ISSUE THREAD

**Issue by JustinDrake** [tanishqjasoria/neth-compose#1]
Consider adding more relays [here](https://github.com/tanishqjasoria/neth-compose/blob/dafbd620b617b6bbeb3e8dbc26d0f65f0b640f53/verkle-refactor/.env#L3), e.g. https://relay.ultrasound.money :)

`https://0xa1559ace749633b997cb3fdacffb890aeebdb0f5a3b6aaa7eeeaf1a38af0a8fe88b9e4b1f61f236d2e64d95733327a62@relay.ultrasound.money`

**Comment by tanishqjasoria** [comment]
this is a repo I mostly use for testing my changes in the nethermind client. 
but since this is a public I can probably add more relays if someone else decides to use this.

**Comment by JustinDrake** [comment]
Understood! Adding more relays would be appreciated if it's an easy job.

**Comment by tanishqjasoria** [comment]
https://github.com/tanishqjasoria/neth-compose/commit/7e874e669d4b99ddd40beb7dbbe56feafce199f8
done

**Comment by JustinDrake** [comment]
Thank you!
